### ISSUE TITLE
Problems with Encoding

### ISSUE THREAD

**Issue by phuesler** [phuesler/payment_dta#7]
```
ban_payment_spec.rb:68: invalid multibyte char (US-ASCII) (SyntaxError)
/Users/phuesler/work/payment_dta/spec/lib/iban_payment_spec.rb:68: invalid multibyte char (US-ASCII)
/Users/phuesler/work/payment_dta/spec/lib/iban_payment_spec.rb:68: syntax error, unexpected $end, expecting ')'
...rtys_address_line3 => '8000 Zürich').
...                               ^
    from /Users/phuesler/.rvm/gems/ruby-1.9.2-p320@payment_dta/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `block in load_spec_files'
    from /Users/phuesler/.rvm/gems/ruby-1.9.2-p320@payment_dta/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `each'
    from /Users/phuesler/.rvm/gems/ruby-1.9.2-p320@payment_dta/gems/rspec-core-2.13.1/lib/rspec/core/configuration.rb:819:in `load_spec_files'
    from /Users/phuesler/.rvm/gems/ruby-1.9.2-p320@payment_dta/gems/rspec-core-2.13.1/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/phuesler/.rvm/gems/ruby-1.9.2-p320@payment_dta/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:80:in `run'
    from /Users/phuesler/.rvm/gems/ruby-1.9.2-p320@payment_dta/gems/rspec-core-2.13.1/lib/rspec/core/runner.rb:17:in `block in autorun'
```

**Comment by phuesler** [comment]
Fixed in (https://github.com/phuesler/payment_dta/commit/ada33c1b1fd1626f70c86f6031ed8e4e0702fc7b)[https://github.com/phuesler/payment_dta/commit/ada33c1b1fd1626f70c86f6031ed8e4e0702fc7b]
